services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:v1.2.3
    container_name: anvil
    entrypoint:
      - anvil
      - --host
      - 0.0.0.0
      - --chain-id
      - "31337"
      - --port
      - "8545"
    ports:
      - "8545:8545"
    networks:
      - pongnet
    environment:
      - FOUNDRY_DISABLE_NIGHTLY_WARNING=1

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: transcendence
    depends_on:
      - anvil
    env_file:
      - ./src/back/.env.backend
      - .env
    volumes:
      - ./contracts/out:/contracts/out
    networks:
      - pongnet

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      args:
        NGINX_USER_NAME: ${NGINX_USER_NAME}
        NGINX_USER_PASSWORD: ${NGINX_USER_PASSWORD}
    container_name: nginx
    env_file:
      - .env
    environment:
      - NGINX_USER_NAME
      - NGINX_USER_PASSWORD
    depends_on:
      - backend
      - prometheus
      - grafana
      - elasticsearch
      - kibana
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - pongnet
      - elknet

  prometheus:
    build:
      context: ./docker/prometheus
      dockerfile: Dockerfile
      args:
        ARCH: x86_64
    container_name: prometheus
    restart: on-failure
    networks:
      - pongnet
    expose:
      - "9090"
    depends_on:
      - nginx-prometheus-exporter
  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    ports:
      - "9091:9091"
    networks:
      - pongnet

  grafana:
    build:
      context: ./docker/grafana
      dockerfile: Dockerfile
    container_name: grafana
    env_file:
      - .env
    restart: on-failure
    environment:
      - GF_SERVER_ROOT_URL
      - GF_SECURITY_ADMIN_USER
      - GF_SECURITY_ADMIN_PASSWORD
      - GF_INSTALL_PLUGINS=grafana-lokiexplore-app
      - GF_AUTH_BASIC_ENABLED=true
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - pongnet
    depends_on:
      - prometheus

  nginx-prometheus-exporter:
    build:
      context: ./docker/nginx-prometheus-exporter
      dockerfile: Dockerfile
      args:
        ARCH: x86_64
    container_name: nginx-prometheus-exporter
    ports:
      - "9113:9113"
    networks:
      - pongnet

  deployer:
    image: ghcr.io/foundry-rs/foundry:v1.2.3
    user: root
    env_file:
      - .env
    environment:
      - PRIVATE_KEY
      - RPC_URL
    working_dir: /contracts
    entrypoint:
      - forge
      - create
      - "--rpc-url=${RPC_URL}"
      - "--private-key=${PRIVATE_KEY}"
      - "--broadcast"
      - src/ScoreBoard.sol:ScoreBoard
    volumes:
      - ./contracts:/contracts
    depends_on:
      - anvil
    networks:
      - pongnet
    restart: "no"
  elasticsearch:
    build:
      context: ./docker/elasticsearch
      dockerfile: Dockerfile
    container_name: es
    ports:
      - "9200"
      - "9300"
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - es-tokens:/usr/share/elasticsearch/config/shared/tokens
      - es-ca:/usr/share/elasticsearch/config/shared/ca
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -k -u elastic:${ES_PASSWORD} https://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=1s >/dev/null 2>&1",
        ]
      interval: 5s
      timeout: 5s
      retries: 50
    restart: on-failure
    networks:
      elknet:
        aliases:
          - elasticsearch # Alias for internal communication
  logstash:
    build:
      context: ./docker/logstash
      dockerfile: Dockerfile
    container_name: logstash
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - LS_JAVA_OPTS=-Xmx256m -Xms256m
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - es-ca:/usr/share/logstash/config/shared/ca:ro
      - es-tokens:/usr/share/logstash/config/shared/tokens:ro
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: on-failure
    networks:
      - elknet
  kibana:
    build:
      context: ./docker/kibana
      dockerfile: Dockerfile
    container_name: kibana
    healthcheck:
      test: curl -s http://localhost:5601/login >/dev/null || exit 1
      interval: 10s
      timeout: 5s
      retries: 20
    ports:
      - "5601"
    environment:
      - ELASTICSEARCH_URL:http://elasticsearch:9200
      - KIBANA_ENCRYPTION_KEY
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - es-tokens:/usr/share/kibana/config/shared/tokens:ro
      - es-ca:/usr/share/kibana/config/shared/ca:ro
    restart: on-failure
    networks:
      - elknet

networks:
  pongnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
  elknet:
    driver: bridge

volumes:
  grafana-data:
  es-tokens:
  es-ca:
