services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: anvil
    entrypoint:
      - anvil
      - --host
      - 0.0.0.0
      - --chain-id
      - "31337"
      - --port
      - "8545"
    ports:
      - "8545:8545"
    networks:
      - pongnet
    environment:
      - FOUNDRY_DISABLE_NIGHTLY_WARNING=1

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: transcendence
    depends_on:
      - anvil
    env_file:
      - ./src/back/.env.backend
      - .env
    volumes:
      - ./contracts/out:/contracts/out
    networks:
      - pongnet

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      args:
        NGINX_USER_NAME: ${NGINX_USER_NAME}
        NGINX_USER_PASSWORD: ${NGINX_USER_PASSWORD}
    container_name: nginx
    env_file:
      - .env
    environment:
      - NGINX_USER_NAME
      - NGINX_USER_PASSWORD
    depends_on:
      - backend
      - prometheus
      - grafana
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - pongnet

  prometheus:
    build:
      context: ./docker/prometheus
      dockerfile: Dockerfile
      args:
        ARCH: x86_64
    container_name: prometheus
    restart: on-failure
    networks:
      - pongnet
    expose:
      - "9090"
    depends_on:
      - nginx-prometheus-exporter
  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    ports:
      - "9091:9091"
    networks:
      - pongnet

  grafana:
    build:
      context: ./docker/grafana
      dockerfile: Dockerfile
    container_name: grafana
    env_file:
      - .env
    restart: on-failure
    environment:
      - GF_SERVER_ROOT_URL
      - GF_SECURITY_ADMIN_USER
      - GF_SECURITY_ADMIN_PASSWORD
      - GF_INSTALL_PLUGINS=grafana-lokiexplore-app
      - GF_AUTH_BASIC_ENABLED=true
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - pongnet
    depends_on:
      - prometheus

  nginx-prometheus-exporter:
    build:
      context: ./docker/nginx-prometheus-exporter
      dockerfile: Dockerfile
      args:
        ARCH: x86_64
    container_name: nginx-prometheus-exporter
    ports:
      - "9113:9113"
    networks:
      - pongnet

  deployer:
    image: ghcr.io/foundry-rs/foundry:latest
    user: root
    env_file:
      - .env
    environment:
      - PRIVATE_KEY
      - RPC_URL
    working_dir: /contracts
    entrypoint:
      - forge
      - create
      - "--rpc-url=${RPC_URL}"
      - "--private-key=${PRIVATE_KEY}"
      - "--broadcast"
      - src/ScoreBoard.sol:ScoreBoard
    volumes:
      - ./contracts:/contracts
    depends_on:
      - anvil
    networks:
      - pongnet
    restart: "no"

networks:
  pongnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

volumes:
  grafana-data:
